# 휠 토크 제한, Back-EMF 감쇄 및 각운동량 적분 모델

from abc import ABC, abstractmethod
import numpy as np

class ActuatorModel(ABC):
    """
    Abstract Base Class for Actuator Models (e.g., Reaction Wheels).
    Adapted from MATLAB ActuatorModel class.
    """

    @abstractmethod
    def get_forces_moments(self, state, actuator_state, current_cg, env_conditions):
        """
        Calculate forces and moments generated by actuators on the spacecraft body.
        Must be implemented in a subclass.
        """
        pass
        
    @abstractmethod
    def actuator_dynamics(self, control_input: np.ndarray, actuator_state: np.ndarray) -> np.ndarray:
        """
        Calculate actuator state derivatives (e.g., wheel acceleration, back-EMF effects).
        Must be implemented in a subclass.
        """
        pass